@server = http://localhost:4004
@auth = Authorization: Basic alice:


### POHeader
# @name POHeader_GET
GET {{server}}/odata/v4/po-overview/POHeader
{{auth}}


### POHeader
# @name POHeader_POST
POST {{server}}/odata/v4/po-overview/POHeader
Content-Type: application/json
{{auth}}

{
  "ID": "30327420-1455-421c-aae1-83805da3747b",
  "PO_Number": 68,
  "CreationDate": "2006-07-17",
  "DeliveryDate": "2011-05-17",
  "Status": 29,
  "MadeBy": "MadeBy-3032742",
  "PCode": "PCode-3032742",
  "CompanyCode": "CompanyCode-3032742",
  "Delete": "2",
  "Criticality": 89,
  "Total_Amount": 80.25,
  "Pl_Master": {
    "CODE": "PlantMaster-3610697"
  },
  "Cp_Master": {
    "CODE": "mpanyMaster-28306358"
  },
  "S_Master": {
    "CODE": 9584453
  },
  "PO_Item_Master": [
    {
      "ID": "19442567-87fd-4b69-8f52-57e22e441257",
      "PO_Number": 93,
      "PO_Item_Num": 47,
      "MCode": "MCode-19442567",
      "Quantity": 10,
      "Amount": 94.71,
      "M_Master": {
        "CODE": "rial_Master-20433308"
      }
    },
    {
      "ID": "19442568-0066-46c3-8751-63383ff516ea",
      "PO_Number": 90,
      "PO_Item_Num": 30,
      "MCode": "MCode-19442568",
      "Quantity": 5,
      "Amount": 36.27,
      "M_Master": {
        "CODE": "rial_Master-20433308"
      }
    }
  ],
  "PO_Attach_Master": [
    {
      "ID": "26303455-0f18-4642-8562-f422781e4380",
      "PO_Number": 71,
      "File_Type": "File_Type-26303455",
      "FileName": "FileName-26303455",
      "createdAt": "2013-10-27T00:00:00.000Z",
      "createdBy": "createdBy.fnrvj@example.net",
      "modifiedAt": "2013-11-28T00:00:00.000Z",
      "modifiedBy": "modifiedBy.fnrvj@example.net"
    },
    {
      "ID": "26303456-3f55-4940-8d23-f7ec7fc2aa72",
      "PO_Number": 87,
      "File_Type": "File_Type-26303456",
      "FileName": "FileName-26303456",
      "createdAt": "2017-04-10T00:00:00.000Z",
      "createdBy": "createdBy.fnrvk@example.com",
      "modifiedAt": "2019-02-04T00:00:00.000Z",
      "modifiedBy": "modifiedBy.fnrvk@example.com"
    }
  ],
  "createdAt": "2018-08-15T00:00:00.000Z",
  "createdBy": "createdBy.1t02u@example.org",
  "modifiedAt": "2004-05-18T00:00:00.000Z",
  "modifiedBy": "modifiedBy.1t02u@example.com"
}


### POHeader
# @name POHeader_PATCH
PATCH {{server}}/odata/v4/po-overview/POHeader/30327420-1455-421c-aae1-83805da3747b
Content-Type: application/json
{{auth}}

{
  "ID": "30327420-1455-421c-aae1-83805da3747b",
  "PO_Number": 68,
  "CreationDate": "2006-07-17",
  "DeliveryDate": "2011-05-17",
  "Status": 29,
  "MadeBy": "MadeBy-3032742",
  "PCode": "PCode-3032742",
  "CompanyCode": "CompanyCode-3032742",
  "Delete": "2",
  "Criticality": 89,
  "Total_Amount": 80.25,
  "Pl_Master": {
    "CODE": "PlantMaster-3610697"
  },
  "Cp_Master": {
    "CODE": "mpanyMaster-28306358"
  },
  "S_Master": {
    "CODE": 9584453
  },
  "PO_Item_Master": [
    {
      "ID": "19442567-87fd-4b69-8f52-57e22e441257",
      "PO_Number": 93,
      "PO_Item_Num": 47,
      "MCode": "MCode-19442567",
      "Quantity": 10,
      "Amount": 94.71,
      "M_Master": {
        "CODE": "rial_Master-20433308"
      }
    },
    {
      "ID": "19442568-0066-46c3-8751-63383ff516ea",
      "PO_Number": 90,
      "PO_Item_Num": 30,
      "MCode": "MCode-19442568",
      "Quantity": 5,
      "Amount": 36.27,
      "M_Master": {
        "CODE": "rial_Master-20433308"
      }
    }
  ],
  "PO_Attach_Master": [
    {
      "ID": "26303455-0f18-4642-8562-f422781e4380",
      "PO_Number": 71,
      "File_Type": "File_Type-26303455",
      "FileName": "FileName-26303455",
      "createdAt": "2013-10-27T00:00:00.000Z",
      "createdBy": "createdBy.fnrvj@example.net",
      "modifiedAt": "2013-11-28T00:00:00.000Z",
      "modifiedBy": "modifiedBy.fnrvj@example.net"
    },
    {
      "ID": "26303456-3f55-4940-8d23-f7ec7fc2aa72",
      "PO_Number": 87,
      "File_Type": "File_Type-26303456",
      "FileName": "FileName-26303456",
      "createdAt": "2017-04-10T00:00:00.000Z",
      "createdBy": "createdBy.fnrvk@example.com",
      "modifiedAt": "2019-02-04T00:00:00.000Z",
      "modifiedBy": "modifiedBy.fnrvk@example.com"
    }
  ],
  "createdAt": "2018-08-15T00:00:00.000Z",
  "createdBy": "createdBy.1t02u@example.org",
  "modifiedAt": "2004-05-18T00:00:00.000Z",
  "modifiedBy": "modifiedBy.1t02u@example.com"
}


### POHeader
# @name POHeader_DELETE
DELETE {{server}}/odata/v4/po-overview/POHeader/30327420-1455-421c-aae1-83805da3747b
Content-Type: application/json
{{auth}}


### POItem
# @name POItem_GET
GET {{server}}/odata/v4/po-overview/POItem
{{auth}}


### POItem
# @name POItem_POST
POST {{server}}/odata/v4/po-overview/POItem
Content-Type: application/json
{{auth}}

{
  "ID": "19442567-87fd-4b69-8f52-57e22e441257",
  "PO_Number": 93,
  "PO_Item_Num": 47,
  "MCode": "MCode-19442567",
  "Quantity": 10,
  "Amount": 94.71,
  "M_Master": {
    "CODE": "rial_Master-20433308"
  }
}


### POItem
# @name POItem_PATCH
PATCH {{server}}/odata/v4/po-overview/POItem/19442567-87fd-4b69-8f52-57e22e441257
Content-Type: application/json
{{auth}}

{
  "ID": "19442567-87fd-4b69-8f52-57e22e441257",
  "PO_Number": 93,
  "PO_Item_Num": 47,
  "MCode": "MCode-19442567",
  "Quantity": 10,
  "Amount": 94.71,
  "M_Master": {
    "CODE": "rial_Master-20433308"
  }
}


### POItem
# @name POItem_DELETE
DELETE {{server}}/odata/v4/po-overview/POItem/19442567-87fd-4b69-8f52-57e22e441257
Content-Type: application/json
{{auth}}


### PlantMaster
# @name PlantMaster_GET
GET {{server}}/odata/v4/po-overview/PlantMaster
{{auth}}


### PlantMaster
# @name PlantMaster_POST
POST {{server}}/odata/v4/po-overview/PlantMaster
Content-Type: application/json
{{auth}}

{
  "CODE": "PlantMaster-3610697",
  "NAME": "NAME-3610697",
  "CITY": "CITY-3610697"
}


### PlantMaster
# @name PlantMaster_PATCH
PATCH {{server}}/odata/v4/po-overview/PlantMaster/PlantMaster-3610697
Content-Type: application/json
{{auth}}

{
  "CODE": "PlantMaster-3610697",
  "NAME": "NAME-3610697",
  "CITY": "CITY-3610697"
}


### PlantMaster
# @name PlantMaster_DELETE
DELETE {{server}}/odata/v4/po-overview/PlantMaster/PlantMaster-3610697
Content-Type: application/json
{{auth}}


### CompanyMaster
# @name CompanyMaster_GET
GET {{server}}/odata/v4/po-overview/CompanyMaster
{{auth}}


### CompanyMaster
# @name CompanyMaster_POST
POST {{server}}/odata/v4/po-overview/CompanyMaster
Content-Type: application/json
{{auth}}

{
  "CODE": "mpanyMaster-28306358",
  "DESC": "DESC-28306358",
  "WEBSITE": "WEBSITE-28306358",
  "NAME": "NAME-28306358"
}


### CompanyMaster
# @name CompanyMaster_PATCH
PATCH {{server}}/odata/v4/po-overview/CompanyMaster/mpanyMaster-28306358
Content-Type: application/json
{{auth}}

{
  "CODE": "mpanyMaster-28306358",
  "DESC": "DESC-28306358",
  "WEBSITE": "WEBSITE-28306358",
  "NAME": "NAME-28306358"
}


### CompanyMaster
# @name CompanyMaster_DELETE
DELETE {{server}}/odata/v4/po-overview/CompanyMaster/mpanyMaster-28306358
Content-Type: application/json
{{auth}}


### POEvent
# @name POEvent_GET
GET {{server}}/odata/v4/po-overview/POEvent
{{auth}}


### POEvent
# @name POEvent_POST
POST {{server}}/odata/v4/po-overview/POEvent
Content-Type: application/json
{{auth}}

{
  "PO_Number": 27643854,
  "EVENT_CODE": 27643854,
  "EVENT_DESCRIPTION": "EVENT_DESCRIPTION-27643854",
  "EVENT_DATE": "2018-05-08T00:00:00.000Z",
  "EVENT_BY": "EVENT_BY-27643854"
}


### POEvent
# @name POEvent_PATCH
PATCH {{server}}/odata/v4/po-overview/POEvent(PO_Number=27643854,EVENT_CODE=27643854)
Content-Type: application/json
{{auth}}

{
  "PO_Number": 27643854,
  "EVENT_CODE": 27643854,
  "EVENT_DESCRIPTION": "EVENT_DESCRIPTION-27643854",
  "EVENT_DATE": "2018-05-08T00:00:00.000Z",
  "EVENT_BY": "EVENT_BY-27643854"
}


### POEvent
# @name POEvent_DELETE
DELETE {{server}}/odata/v4/po-overview/POEvent(PO_Number=27643854,EVENT_CODE=27643854)
Content-Type: application/json
{{auth}}


### Material_Master
# @name Material_Master_GET
GET {{server}}/odata/v4/po-overview/Material_Master
{{auth}}


### Material_Master
# @name Material_Master_POST
POST {{server}}/odata/v4/po-overview/Material_Master
Content-Type: application/json
{{auth}}

{
  "CODE": "rial_Master-20433308",
  "DESC": "DESC-20433308",
  "Plant_Code": "Plant_Code-20433308",
  "Price": 49.15989408,
  "Material_Image": "Material_Image-20433308",
  "Pl_Master": {
    "CODE": "PlantMaster-3610697"
  },
  "Phone": "Phone-20433308",
  "Fax": "Fax-20433308",
  "Email": "Email.c5yfw@example.net",
  "LandLine": "LandLine-20433308"
}


### Material_Master
# @name Material_Master_PATCH
PATCH {{server}}/odata/v4/po-overview/Material_Master/rial_Master-20433308
Content-Type: application/json
{{auth}}

{
  "CODE": "rial_Master-20433308",
  "DESC": "DESC-20433308",
  "Plant_Code": "Plant_Code-20433308",
  "Price": 49.15989408,
  "Material_Image": "Material_Image-20433308",
  "Pl_Master": {
    "CODE": "PlantMaster-3610697"
  },
  "Phone": "Phone-20433308",
  "Fax": "Fax-20433308",
  "Email": "Email.c5yfw@example.net",
  "LandLine": "LandLine-20433308"
}


### Material_Master
# @name Material_Master_DELETE
DELETE {{server}}/odata/v4/po-overview/Material_Master/rial_Master-20433308
Content-Type: application/json
{{auth}}


### StatusMaster
# @name StatusMaster_GET
GET {{server}}/odata/v4/po-overview/StatusMaster
{{auth}}


### StatusMaster
# @name StatusMaster_POST
POST {{server}}/odata/v4/po-overview/StatusMaster
Content-Type: application/json
{{auth}}

{
  "CODE": 9584453,
  "DESC": "DESC-9584453"
}


### StatusMaster
# @name StatusMaster_PATCH
PATCH {{server}}/odata/v4/po-overview/StatusMaster/9584453
Content-Type: application/json
{{auth}}

{
  "CODE": 9584453,
  "DESC": "DESC-9584453"
}


### StatusMaster
# @name StatusMaster_DELETE
DELETE {{server}}/odata/v4/po-overview/StatusMaster/9584453
Content-Type: application/json
{{auth}}


### POStarReport
# @name POStarReport_GET
GET {{server}}/odata/v4/po-overview/POStarReport
{{auth}}


### PO_Header_Items
# @name PO_Header_Items_GET
GET {{server}}/odata/v4/po-overview/PO_Header_Items
{{auth}}


### PO_Attachment
# @name PO_Attachment_GET
GET {{server}}/odata/v4/po-overview/PO_Attachment
{{auth}}


### PO_Attachment
# @name PO_Attachment_POST
POST {{server}}/odata/v4/po-overview/PO_Attachment
Content-Type: application/json
{{auth}}

{
  "ID": "26303455-0f18-4642-8562-f422781e4380",
  "PO_Number": 71,
  "File_Type": "File_Type-26303455",
  "FileName": "FileName-26303455",
  "createdAt": "2013-10-27T00:00:00.000Z",
  "createdBy": "createdBy.fnrvj@example.net",
  "modifiedAt": "2013-11-28T00:00:00.000Z",
  "modifiedBy": "modifiedBy.fnrvj@example.net"
}


### PO_Attachment
# @name PO_Attachment_PATCH
PATCH {{server}}/odata/v4/po-overview/PO_Attachment/26303455-0f18-4642-8562-f422781e4380
Content-Type: application/json
{{auth}}

{
  "ID": "26303455-0f18-4642-8562-f422781e4380",
  "PO_Number": 71,
  "File_Type": "File_Type-26303455",
  "FileName": "FileName-26303455",
  "createdAt": "2013-10-27T00:00:00.000Z",
  "createdBy": "createdBy.fnrvj@example.net",
  "modifiedAt": "2013-11-28T00:00:00.000Z",
  "modifiedBy": "modifiedBy.fnrvj@example.net"
}


### PO_Attachment
# @name PO_Attachment_DELETE
DELETE {{server}}/odata/v4/po-overview/PO_Attachment/26303455-0f18-4642-8562-f422781e4380
Content-Type: application/json
{{auth}}
