@server = http://localhost:4004
@auth = Authorization: Basic alice:


### POHeader
# @name POHeader_GET
GET {{server}}/odata/v4/poapproval/POHeader
{{auth}}


### POHeader Drafts GET
# @name POHeader_Drafts_GET
GET {{server}}/odata/v4/poapproval/POHeader?$filter=(IsActiveEntity eq false)
{{auth}}


### POHeader Draft POST
# @name POHeader_Draft_POST
POST {{server}}/odata/v4/poapproval/POHeader
Content-Type: application/json
{{auth}}

{
  "PO_Number": 1,
  "CreationDate": "2016-09-01",
  "DeliveryDate": "2014-02-08",
  "Status": 92,
  "MadeBy": "MadeBy-2601",
  "PCode": "PCode-2601",
  "CompanyCode": "CompanyCode-2601",
  "Delete": "1",
  "Criticality": 19,
  "Total_Amount": 69.26,
  "Pl_Master": {
    "CODE": "PlantMaster-29435033"
  },
  "Cp_Master": {
    "CODE": "mpanyMaster-18706400"
  },
  "S_Master": {
    "CODE": 13581456
  },
  "PO_Item_Master": [
    {
      "ID": "16837856-0081-4ad7-9f91-00dee2630ac6",
      "PO_Number": 99,
      "PO_Item_Num": 19,
      "MCode": "MCode-16837856",
      "Quantity": 60,
      "Amount": 12.13,
      "M_Master": {
        "CODE": "rial_Master-26011330"
      }
    },
    {
      "ID": "16837857-9b0d-462a-8c5a-c9fffc603a32",
      "PO_Number": 81,
      "PO_Item_Num": 93,
      "MCode": "MCode-16837857",
      "Quantity": 90,
      "Amount": 48.15,
      "M_Master": {
        "CODE": "rial_Master-26011330"
      }
    }
  ],
  "PO_Attach_Master": [
    {
      "ID": "31620627-5ae3-4eac-ac25-3a7bec4b9116",
      "PO_Number": 1,
      "File_Type": "File_Type-31620627",
      "FileName": "FileName-31620627",
      "createdAt": "2012-11-06T00:00:00.000Z",
      "createdBy": "createdBy.itqmr@example.net",
      "modifiedAt": "2001-03-20T00:00:00.000Z",
      "modifiedBy": "modifiedBy.itqmr@example.com"
    },
    {
      "ID": "31620628-010d-4235-9284-29738971b752",
      "PO_Number": 49,
      "File_Type": "File_Type-31620628",
      "FileName": "FileName-31620628",
      "createdAt": "2006-06-21T00:00:00.000Z",
      "createdBy": "createdBy.itqms@example.org",
      "modifiedAt": "2009-10-05T00:00:00.000Z",
      "modifiedBy": "modifiedBy.itqms@example.net"
    }
  ],
  "PO_Label": "PO_Label-2601",
  "createdAt": "2018-02-11T00:00:00.000Z",
  "createdBy": "createdBy.209@example.com",
  "modifiedAt": "2012-01-01T00:00:00.000Z",
  "modifiedBy": "modifiedBy.209@example.com"
}


### Result from POST request above
@draftID = {{POHeader_Draft_POST.response.body.$.ID}}


### POHeader Draft PATCH
# @name POHeader_Draft_Patch
PATCH {{server}}/odata/v4/poapproval/POHeader(ID={{draftID}},IsActiveEntity=false)
Content-Type: application/json
{{auth}}

{
  "PO_Number": 1,
  "CreationDate": "2016-09-01",
  "DeliveryDate": "2014-02-08",
  "Status": 92,
  "MadeBy": "MadeBy-2601",
  "PCode": "PCode-2601",
  "CompanyCode": "CompanyCode-2601",
  "Delete": "1",
  "Criticality": 19,
  "Total_Amount": 69.26,
  "Pl_Master": {
    "CODE": "PlantMaster-29435033"
  },
  "Cp_Master": {
    "CODE": "mpanyMaster-18706400"
  },
  "S_Master": {
    "CODE": 13581456
  },
  "PO_Item_Master": [
    {
      "ID": "16837856-0081-4ad7-9f91-00dee2630ac6",
      "PO_Number": 99,
      "PO_Item_Num": 19,
      "MCode": "MCode-16837856",
      "Quantity": 60,
      "Amount": 12.13,
      "M_Master": {
        "CODE": "rial_Master-26011330"
      }
    },
    {
      "ID": "16837857-9b0d-462a-8c5a-c9fffc603a32",
      "PO_Number": 81,
      "PO_Item_Num": 93,
      "MCode": "MCode-16837857",
      "Quantity": 90,
      "Amount": 48.15,
      "M_Master": {
        "CODE": "rial_Master-26011330"
      }
    }
  ],
  "PO_Attach_Master": [
    {
      "ID": "31620627-5ae3-4eac-ac25-3a7bec4b9116",
      "PO_Number": 1,
      "File_Type": "File_Type-31620627",
      "FileName": "FileName-31620627",
      "createdAt": "2012-11-06T00:00:00.000Z",
      "createdBy": "createdBy.itqmr@example.net",
      "modifiedAt": "2001-03-20T00:00:00.000Z",
      "modifiedBy": "modifiedBy.itqmr@example.com"
    },
    {
      "ID": "31620628-010d-4235-9284-29738971b752",
      "PO_Number": 49,
      "File_Type": "File_Type-31620628",
      "FileName": "FileName-31620628",
      "createdAt": "2006-06-21T00:00:00.000Z",
      "createdBy": "createdBy.itqms@example.org",
      "modifiedAt": "2009-10-05T00:00:00.000Z",
      "modifiedBy": "modifiedBy.itqms@example.net"
    }
  ],
  "PO_Label": "PO_Label-2601",
  "createdAt": "2018-02-11T00:00:00.000Z",
  "createdBy": "createdBy.209@example.com",
  "modifiedAt": "2012-01-01T00:00:00.000Z",
  "modifiedBy": "modifiedBy.209@example.com"
}


### POHeader Draft Prepare
# @name POHeader_Draft_Prepare
POST {{server}}/odata/v4/poapproval/POHeader(ID={{draftID}},IsActiveEntity=false)/AdminService.draftPrepare
Content-Type: application/json
{{auth}}

{}


### POHeader Draft Activate
# @name POHeader_Draft_Activate
POST {{server}}/odata/v4/poapproval/POHeader(ID={{draftID}},IsActiveEntity=false)/AdminService.draftActivate
Content-Type: application/json
{{auth}}

{}


### POItem
# @name POItem_GET
GET {{server}}/odata/v4/poapproval/POItem
{{auth}}


### POItem
# @name POItem_POST
POST {{server}}/odata/v4/poapproval/POItem
Content-Type: application/json
{{auth}}

{
  "ID": "16837856-0081-4ad7-9f91-00dee2630ac6",
  "PO_Number": 99,
  "PO_Item_Num": 19,
  "MCode": "MCode-16837856",
  "Quantity": 60,
  "Amount": 12.13,
  "M_Master": {
    "CODE": "rial_Master-26011330"
  }
}


### POItem
# @name POItem_PATCH
PATCH {{server}}/odata/v4/poapproval/POItem/16837856-0081-4ad7-9f91-00dee2630ac6
Content-Type: application/json
{{auth}}

{
  "ID": "16837856-0081-4ad7-9f91-00dee2630ac6",
  "PO_Number": 99,
  "PO_Item_Num": 19,
  "MCode": "MCode-16837856",
  "Quantity": 60,
  "Amount": 12.13,
  "M_Master": {
    "CODE": "rial_Master-26011330"
  }
}


### POItem
# @name POItem_DELETE
DELETE {{server}}/odata/v4/poapproval/POItem/16837856-0081-4ad7-9f91-00dee2630ac6
Content-Type: application/json
{{auth}}


### PlantMaster
# @name PlantMaster_GET
GET {{server}}/odata/v4/poapproval/PlantMaster
{{auth}}


### PlantMaster
# @name PlantMaster_POST
POST {{server}}/odata/v4/poapproval/PlantMaster
Content-Type: application/json
{{auth}}

{
  "CODE": "PlantMaster-29435033",
  "NAME": "NAME-29435033",
  "CITY": "CITY-29435033"
}


### PlantMaster
# @name PlantMaster_PATCH
PATCH {{server}}/odata/v4/poapproval/PlantMaster/PlantMaster-29435033
Content-Type: application/json
{{auth}}

{
  "CODE": "PlantMaster-29435033",
  "NAME": "NAME-29435033",
  "CITY": "CITY-29435033"
}


### PlantMaster
# @name PlantMaster_DELETE
DELETE {{server}}/odata/v4/poapproval/PlantMaster/PlantMaster-29435033
Content-Type: application/json
{{auth}}


### CompanyMaster
# @name CompanyMaster_GET
GET {{server}}/odata/v4/poapproval/CompanyMaster
{{auth}}


### CompanyMaster
# @name CompanyMaster_POST
POST {{server}}/odata/v4/poapproval/CompanyMaster
Content-Type: application/json
{{auth}}

{
  "CODE": "mpanyMaster-18706400",
  "DESC": "DESC-18706400",
  "WEBSITE": "WEBSITE-18706400",
  "NAME": "NAME-18706400"
}


### CompanyMaster
# @name CompanyMaster_PATCH
PATCH {{server}}/odata/v4/poapproval/CompanyMaster/mpanyMaster-18706400
Content-Type: application/json
{{auth}}

{
  "CODE": "mpanyMaster-18706400",
  "DESC": "DESC-18706400",
  "WEBSITE": "WEBSITE-18706400",
  "NAME": "NAME-18706400"
}


### CompanyMaster
# @name CompanyMaster_DELETE
DELETE {{server}}/odata/v4/poapproval/CompanyMaster/mpanyMaster-18706400
Content-Type: application/json
{{auth}}


### POEvent
# @name POEvent_GET
GET {{server}}/odata/v4/poapproval/POEvent
{{auth}}


### POEvent
# @name POEvent_POST
POST {{server}}/odata/v4/poapproval/POEvent
Content-Type: application/json
{{auth}}

{
  "PO_Number": 18680701,
  "EVENT_CODE": 18680701,
  "EVENT_DESCRIPTION": "EVENT_DESCRIPTION-18680701",
  "EVENT_DATE": "2000-10-21T00:00:00.000Z",
  "EVENT_BY": "EVENT_BY-18680701"
}


### POEvent
# @name POEvent_PATCH
PATCH {{server}}/odata/v4/poapproval/POEvent(PO_Number=18680701,EVENT_CODE=18680701)
Content-Type: application/json
{{auth}}

{
  "PO_Number": 18680701,
  "EVENT_CODE": 18680701,
  "EVENT_DESCRIPTION": "EVENT_DESCRIPTION-18680701",
  "EVENT_DATE": "2000-10-21T00:00:00.000Z",
  "EVENT_BY": "EVENT_BY-18680701"
}


### POEvent
# @name POEvent_DELETE
DELETE {{server}}/odata/v4/poapproval/POEvent(PO_Number=18680701,EVENT_CODE=18680701)
Content-Type: application/json
{{auth}}


### Material_Master
# @name Material_Master_GET
GET {{server}}/odata/v4/poapproval/Material_Master
{{auth}}


### Material_Master
# @name Material_Master_POST
POST {{server}}/odata/v4/poapproval/Material_Master
Content-Type: application/json
{{auth}}

{
  "CODE": "rial_Master-26011330",
  "DESC": "DESC-26011330",
  "Plant_Code": "Plant_Code-26011330",
  "Price": 96.31085925,
  "Material_Image": "Material_Image-26011330",
  "Pl_Master": {
    "CODE": "PlantMaster-29435033"
  },
  "Phone": "Phone-26011330",
  "Fax": "Fax-26011330",
  "Email": "Email.fhigy@example.org",
  "LandLine": "LandLine-26011330"
}


### Material_Master
# @name Material_Master_PATCH
PATCH {{server}}/odata/v4/poapproval/Material_Master/rial_Master-26011330
Content-Type: application/json
{{auth}}

{
  "CODE": "rial_Master-26011330",
  "DESC": "DESC-26011330",
  "Plant_Code": "Plant_Code-26011330",
  "Price": 96.31085925,
  "Material_Image": "Material_Image-26011330",
  "Pl_Master": {
    "CODE": "PlantMaster-29435033"
  },
  "Phone": "Phone-26011330",
  "Fax": "Fax-26011330",
  "Email": "Email.fhigy@example.org",
  "LandLine": "LandLine-26011330"
}


### Material_Master
# @name Material_Master_DELETE
DELETE {{server}}/odata/v4/poapproval/Material_Master/rial_Master-26011330
Content-Type: application/json
{{auth}}


### StatusMaster
# @name StatusMaster_GET
GET {{server}}/odata/v4/poapproval/StatusMaster
{{auth}}


### StatusMaster
# @name StatusMaster_POST
POST {{server}}/odata/v4/poapproval/StatusMaster
Content-Type: application/json
{{auth}}

{
  "CODE": 13581456,
  "DESC": "DESC-13581456"
}


### StatusMaster
# @name StatusMaster_PATCH
PATCH {{server}}/odata/v4/poapproval/StatusMaster/13581456
Content-Type: application/json
{{auth}}

{
  "CODE": 13581456,
  "DESC": "DESC-13581456"
}


### StatusMaster
# @name StatusMaster_DELETE
DELETE {{server}}/odata/v4/poapproval/StatusMaster/13581456
Content-Type: application/json
{{auth}}


### ApproverMaster
# @name ApproverMaster_GET
GET {{server}}/odata/v4/poapproval/ApproverMaster
{{auth}}


### ApproverMaster
# @name ApproverMaster_POST
POST {{server}}/odata/v4/poapproval/ApproverMaster
Content-Type: application/json
{{auth}}

{
  "USER_NAME": "roverMaster-16355584",
  "NAME": "NAME-16355584",
  "PASSCODE": "PASSCODE-16355584",
  "LEVEL": 35
}


### ApproverMaster
# @name ApproverMaster_PATCH
PATCH {{server}}/odata/v4/poapproval/ApproverMaster/roverMaster-16355584
Content-Type: application/json
{{auth}}

{
  "USER_NAME": "roverMaster-16355584",
  "NAME": "NAME-16355584",
  "PASSCODE": "PASSCODE-16355584",
  "LEVEL": 35
}


### ApproverMaster
# @name ApproverMaster_DELETE
DELETE {{server}}/odata/v4/poapproval/ApproverMaster/roverMaster-16355584
Content-Type: application/json
{{auth}}


### PO_Attachment
# @name PO_Attachment_GET
GET {{server}}/odata/v4/poapproval/PO_Attachment
{{auth}}


### PO_Attachment
# @name PO_Attachment_POST
POST {{server}}/odata/v4/poapproval/PO_Attachment
Content-Type: application/json
{{auth}}

{
  "ID": "31620627-5ae3-4eac-ac25-3a7bec4b9116",
  "PO_Number": 1,
  "File_Type": "File_Type-31620627",
  "FileName": "FileName-31620627",
  "createdAt": "2012-11-06T00:00:00.000Z",
  "createdBy": "createdBy.itqmr@example.net",
  "modifiedAt": "2001-03-20T00:00:00.000Z",
  "modifiedBy": "modifiedBy.itqmr@example.com"
}


### PO_Attachment
# @name PO_Attachment_PATCH
PATCH {{server}}/odata/v4/poapproval/PO_Attachment/31620627-5ae3-4eac-ac25-3a7bec4b9116
Content-Type: application/json
{{auth}}

{
  "ID": "31620627-5ae3-4eac-ac25-3a7bec4b9116",
  "PO_Number": 1,
  "File_Type": "File_Type-31620627",
  "FileName": "FileName-31620627",
  "createdAt": "2012-11-06T00:00:00.000Z",
  "createdBy": "createdBy.itqmr@example.net",
  "modifiedAt": "2001-03-20T00:00:00.000Z",
  "modifiedBy": "modifiedBy.itqmr@example.com"
}


### PO_Attachment
# @name PO_Attachment_DELETE
DELETE {{server}}/odata/v4/poapproval/PO_Attachment/31620627-5ae3-4eac-ac25-3a7bec4b9116
Content-Type: application/json
{{auth}}


### POApprove
# @name POApprove_POST
POST {{server}}/odata/v4/poapproval/POApprove
Content-Type: application/json
{{auth}}

{
  "input": null
}


### POComplete
# @name POComplete_POST
POST {{server}}/odata/v4/poapproval/POComplete
Content-Type: application/json
{{auth}}

{
  "input": null
}


### POReject
# @name POReject_POST
POST {{server}}/odata/v4/poapproval/POReject
Content-Type: application/json
{{auth}}

{
  "input": null
}
