@server = http://localhost:4004
@auth = Authorization: Basic alice:


### POHeader
# @name POHeader_GET
GET {{server}}/odata/v4/poodata/POHeader
{{auth}}


### POItem
# @name POItem_GET
GET {{server}}/odata/v4/poodata/POItem
{{auth}}


### PlantMaster
# @name PlantMaster_GET
GET {{server}}/odata/v4/poodata/PlantMaster
{{auth}}


### PlantMaster
# @name PlantMaster_POST
POST {{server}}/odata/v4/poodata/PlantMaster
Content-Type: application/json
{{auth}}

{
  "CODE": "PlantMaster-20568444",
  "NAME": "NAME-20568444",
  "CITY": "CITY-20568444"
}


### PlantMaster
# @name PlantMaster_PATCH
PATCH {{server}}/odata/v4/poodata/PlantMaster/PlantMaster-20568444
Content-Type: application/json
{{auth}}

{
  "CODE": "PlantMaster-20568444",
  "NAME": "NAME-20568444",
  "CITY": "CITY-20568444"
}


### PlantMaster
# @name PlantMaster_DELETE
DELETE {{server}}/odata/v4/poodata/PlantMaster/PlantMaster-20568444
Content-Type: application/json
{{auth}}


### CompanyMaster
# @name CompanyMaster_GET
GET {{server}}/odata/v4/poodata/CompanyMaster
{{auth}}


### CompanyMaster
# @name CompanyMaster_POST
POST {{server}}/odata/v4/poodata/CompanyMaster
Content-Type: application/json
{{auth}}

{
  "CODE": "mpanyMaster-19943092",
  "DESC": "DESC-19943092",
  "WEBSITE": "WEBSITE-19943092",
  "NAME": "NAME-19943092"
}


### CompanyMaster
# @name CompanyMaster_PATCH
PATCH {{server}}/odata/v4/poodata/CompanyMaster/mpanyMaster-19943092
Content-Type: application/json
{{auth}}

{
  "CODE": "mpanyMaster-19943092",
  "DESC": "DESC-19943092",
  "WEBSITE": "WEBSITE-19943092",
  "NAME": "NAME-19943092"
}


### CompanyMaster
# @name CompanyMaster_DELETE
DELETE {{server}}/odata/v4/poodata/CompanyMaster/mpanyMaster-19943092
Content-Type: application/json
{{auth}}


### POEvent
# @name POEvent_GET
GET {{server}}/odata/v4/poodata/POEvent
{{auth}}


### POEvent
# @name POEvent_POST
POST {{server}}/odata/v4/poodata/POEvent
Content-Type: application/json
{{auth}}

{
  "PO_Number": 27921880,
  "EVENT_CODE": 27921880,
  "EVENT_DESCRIPTION": "EVENT_DESCRIPTION-27921880",
  "EVENT_DATE": "2003-02-27T00:00:00.000Z",
  "EVENT_BY": "EVENT_BY-27921880"
}


### POEvent
# @name POEvent_PATCH
PATCH {{server}}/odata/v4/poodata/POEvent(PO_Number=27921880,EVENT_CODE=27921880)
Content-Type: application/json
{{auth}}

{
  "PO_Number": 27921880,
  "EVENT_CODE": 27921880,
  "EVENT_DESCRIPTION": "EVENT_DESCRIPTION-27921880",
  "EVENT_DATE": "2003-02-27T00:00:00.000Z",
  "EVENT_BY": "EVENT_BY-27921880"
}


### POEvent
# @name POEvent_DELETE
DELETE {{server}}/odata/v4/poodata/POEvent(PO_Number=27921880,EVENT_CODE=27921880)
Content-Type: application/json
{{auth}}


### Material_Master
# @name Material_Master_GET
GET {{server}}/odata/v4/poodata/Material_Master
{{auth}}


### Material_Master
# @name Material_Master_POST
POST {{server}}/odata/v4/poodata/Material_Master
Content-Type: application/json
{{auth}}

{
  "CODE": "rial_Master-19769799",
  "DESC": "DESC-19769799",
  "Plant_Code": "Plant_Code-19769799",
  "Price": 91.8651986,
  "Material_Image": "Material_Image-19769799",
  "Pl_Master": {
    "CODE": "PlantMaster-20568444"
  },
  "Phone": "Phone-19769799",
  "Fax": "Fax-19769799",
  "Email": "Email.brqh3@example.org",
  "LandLine": "LandLine-19769799"
}


### Material_Master
# @name Material_Master_PATCH
PATCH {{server}}/odata/v4/poodata/Material_Master/rial_Master-19769799
Content-Type: application/json
{{auth}}

{
  "CODE": "rial_Master-19769799",
  "DESC": "DESC-19769799",
  "Plant_Code": "Plant_Code-19769799",
  "Price": 91.8651986,
  "Material_Image": "Material_Image-19769799",
  "Pl_Master": {
    "CODE": "PlantMaster-20568444"
  },
  "Phone": "Phone-19769799",
  "Fax": "Fax-19769799",
  "Email": "Email.brqh3@example.org",
  "LandLine": "LandLine-19769799"
}


### Material_Master
# @name Material_Master_DELETE
DELETE {{server}}/odata/v4/poodata/Material_Master/rial_Master-19769799
Content-Type: application/json
{{auth}}


### StatusMaster
# @name StatusMaster_GET
GET {{server}}/odata/v4/poodata/StatusMaster
{{auth}}


### StatusMaster
# @name StatusMaster_POST
POST {{server}}/odata/v4/poodata/StatusMaster
Content-Type: application/json
{{auth}}

{
  "CODE": 15172714,
  "DESC": "DESC-15172714"
}


### StatusMaster
# @name StatusMaster_PATCH
PATCH {{server}}/odata/v4/poodata/StatusMaster/15172714
Content-Type: application/json
{{auth}}

{
  "CODE": 15172714,
  "DESC": "DESC-15172714"
}


### StatusMaster
# @name StatusMaster_DELETE
DELETE {{server}}/odata/v4/poodata/StatusMaster/15172714
Content-Type: application/json
{{auth}}


### PO_Attachment
# @name PO_Attachment_GET
GET {{server}}/odata/v4/poodata/PO_Attachment
{{auth}}


### PO_Attachment
# @name PO_Attachment_POST
POST {{server}}/odata/v4/poodata/PO_Attachment
Content-Type: application/json
{{auth}}

{
  "ID": "22690355-c841-4c4a-8721-f34c713a3bb5",
  "PO_Number": 34,
  "File_Type": "File_Type-22690355",
  "FileName": "FileName-22690355",
  "createdAt": "2002-04-04T00:00:00.000Z",
  "createdBy": "createdBy.dibzn@example.com",
  "modifiedAt": "2002-12-20T00:00:00.000Z",
  "modifiedBy": "modifiedBy.dibzn@example.com"
}


### PO_Attachment
# @name PO_Attachment_PATCH
PATCH {{server}}/odata/v4/poodata/PO_Attachment/22690355-c841-4c4a-8721-f34c713a3bb5
Content-Type: application/json
{{auth}}

{
  "ID": "22690355-c841-4c4a-8721-f34c713a3bb5",
  "PO_Number": 34,
  "File_Type": "File_Type-22690355",
  "FileName": "FileName-22690355",
  "createdAt": "2002-04-04T00:00:00.000Z",
  "createdBy": "createdBy.dibzn@example.com",
  "modifiedAt": "2002-12-20T00:00:00.000Z",
  "modifiedBy": "modifiedBy.dibzn@example.com"
}


### PO_Attachment
# @name PO_Attachment_DELETE
DELETE {{server}}/odata/v4/poodata/PO_Attachment/22690355-c841-4c4a-8721-f34c713a3bb5
Content-Type: application/json
{{auth}}
