@server = http://localhost:4004
@auth = Authorization: Basic alice:


### POHeader
# @name POHeader_GET
GET {{server}}/odata/v4/poplain/POHeader
{{auth}}


### POHeader
# @name POHeader_POST
POST {{server}}/odata/v4/poplain/POHeader
Content-Type: application/json
{{auth}}

{
  "ID": "69721001-fc4d-473b-928f-bd161e1a7127",
  "PO_Number": 19,
  "CreationDate": "2017-09-02",
  "DeliveryDate": "2018-06-24",
  "Status": 40,
  "MadeBy": "MadeBy-6972100",
  "PCode": "PCode-6972100",
  "CompanyCode": "CompanyCode-6972100",
  "Delete": "0",
  "Criticality": 39,
  "Total_Amount": 40.18,
  "Pl_Master": {
    "CODE": "PlantMaster-25224524"
  },
  "Cp_Master": {
    "CODE": "mpanyMaster-27004309"
  },
  "S_Master": {
    "CODE": 18168879
  },
  "PO_Item_Master": [
    {
      "ID": "29644194-8e34-4163-a7db-27da200f6948",
      "PO_Number": 69,
      "PO_Item_Num": 9,
      "MCode": "MCode-29644194",
      "Quantity": 69,
      "Amount": 32.91,
      "M_Master": {
        "CODE": "erial_Master-5808563"
      }
    },
    {
      "ID": "29644195-0575-460c-a868-936a1910c18a",
      "PO_Number": 1,
      "PO_Item_Num": 0,
      "MCode": "MCode-29644195",
      "Quantity": 26,
      "Amount": 58.28,
      "M_Master": {
        "CODE": "erial_Master-5808563"
      }
    }
  ],
  "PO_Attach_Master": [
    {
      "ID": "1113953e-db6d-4f0b-9647-c7d259d4bb71",
      "PO_Number": 86,
      "File_Type": "File_Type-1113953",
      "FileName": "FileName-1113953",
      "createdAt": "2001-01-17T00:00:00.000Z",
      "createdBy": "createdBy.nvj5@example.org",
      "modifiedAt": "2013-02-19T00:00:00.000Z",
      "modifiedBy": "modifiedBy.nvj5@example.net"
    },
    {
      "ID": "1113954e-761b-4f0f-b09e-48a9f3586c62",
      "PO_Number": 54,
      "File_Type": "File_Type-1113954",
      "FileName": "FileName-1113954",
      "createdAt": "2013-01-09T00:00:00.000Z",
      "createdBy": "createdBy.nvj6@example.org",
      "modifiedAt": "2016-10-11T00:00:00.000Z",
      "modifiedBy": "modifiedBy.nvj6@example.net"
    }
  ],
  "createdAt": "2014-05-14T00:00:00.000Z",
  "createdBy": "createdBy.45fpg@example.net",
  "modifiedAt": "2011-08-04T00:00:00.000Z",
  "modifiedBy": "modifiedBy.45fpg@example.com"
}


### POHeader
# @name POHeader_PATCH
PATCH {{server}}/odata/v4/poplain/POHeader/69721001-fc4d-473b-928f-bd161e1a7127
Content-Type: application/json
{{auth}}

{
  "ID": "69721001-fc4d-473b-928f-bd161e1a7127",
  "PO_Number": 19,
  "CreationDate": "2017-09-02",
  "DeliveryDate": "2018-06-24",
  "Status": 40,
  "MadeBy": "MadeBy-6972100",
  "PCode": "PCode-6972100",
  "CompanyCode": "CompanyCode-6972100",
  "Delete": "0",
  "Criticality": 39,
  "Total_Amount": 40.18,
  "Pl_Master": {
    "CODE": "PlantMaster-25224524"
  },
  "Cp_Master": {
    "CODE": "mpanyMaster-27004309"
  },
  "S_Master": {
    "CODE": 18168879
  },
  "PO_Item_Master": [
    {
      "ID": "29644194-8e34-4163-a7db-27da200f6948",
      "PO_Number": 69,
      "PO_Item_Num": 9,
      "MCode": "MCode-29644194",
      "Quantity": 69,
      "Amount": 32.91,
      "M_Master": {
        "CODE": "erial_Master-5808563"
      }
    },
    {
      "ID": "29644195-0575-460c-a868-936a1910c18a",
      "PO_Number": 1,
      "PO_Item_Num": 0,
      "MCode": "MCode-29644195",
      "Quantity": 26,
      "Amount": 58.28,
      "M_Master": {
        "CODE": "erial_Master-5808563"
      }
    }
  ],
  "PO_Attach_Master": [
    {
      "ID": "1113953e-db6d-4f0b-9647-c7d259d4bb71",
      "PO_Number": 86,
      "File_Type": "File_Type-1113953",
      "FileName": "FileName-1113953",
      "createdAt": "2001-01-17T00:00:00.000Z",
      "createdBy": "createdBy.nvj5@example.org",
      "modifiedAt": "2013-02-19T00:00:00.000Z",
      "modifiedBy": "modifiedBy.nvj5@example.net"
    },
    {
      "ID": "1113954e-761b-4f0f-b09e-48a9f3586c62",
      "PO_Number": 54,
      "File_Type": "File_Type-1113954",
      "FileName": "FileName-1113954",
      "createdAt": "2013-01-09T00:00:00.000Z",
      "createdBy": "createdBy.nvj6@example.org",
      "modifiedAt": "2016-10-11T00:00:00.000Z",
      "modifiedBy": "modifiedBy.nvj6@example.net"
    }
  ],
  "createdAt": "2014-05-14T00:00:00.000Z",
  "createdBy": "createdBy.45fpg@example.net",
  "modifiedAt": "2011-08-04T00:00:00.000Z",
  "modifiedBy": "modifiedBy.45fpg@example.com"
}


### POHeader
# @name POHeader_DELETE
DELETE {{server}}/odata/v4/poplain/POHeader/69721001-fc4d-473b-928f-bd161e1a7127
Content-Type: application/json
{{auth}}


### POItem
# @name POItem_GET
GET {{server}}/odata/v4/poplain/POItem
{{auth}}


### POItem
# @name POItem_POST
POST {{server}}/odata/v4/poplain/POItem
Content-Type: application/json
{{auth}}

{
  "ID": "29644194-8e34-4163-a7db-27da200f6948",
  "PO_Number": 69,
  "PO_Item_Num": 9,
  "MCode": "MCode-29644194",
  "Quantity": 69,
  "Amount": 32.91,
  "M_Master": {
    "CODE": "erial_Master-5808563"
  }
}


### POItem
# @name POItem_PATCH
PATCH {{server}}/odata/v4/poplain/POItem/29644194-8e34-4163-a7db-27da200f6948
Content-Type: application/json
{{auth}}

{
  "ID": "29644194-8e34-4163-a7db-27da200f6948",
  "PO_Number": 69,
  "PO_Item_Num": 9,
  "MCode": "MCode-29644194",
  "Quantity": 69,
  "Amount": 32.91,
  "M_Master": {
    "CODE": "erial_Master-5808563"
  }
}


### POItem
# @name POItem_DELETE
DELETE {{server}}/odata/v4/poplain/POItem/29644194-8e34-4163-a7db-27da200f6948
Content-Type: application/json
{{auth}}


### PlantMaster
# @name PlantMaster_GET
GET {{server}}/odata/v4/poplain/PlantMaster
{{auth}}


### PlantMaster
# @name PlantMaster_POST
POST {{server}}/odata/v4/poplain/PlantMaster
Content-Type: application/json
{{auth}}

{
  "CODE": "PlantMaster-25224524",
  "NAME": "NAME-25224524",
  "CITY": "CITY-25224524"
}


### PlantMaster
# @name PlantMaster_PATCH
PATCH {{server}}/odata/v4/poplain/PlantMaster/PlantMaster-25224524
Content-Type: application/json
{{auth}}

{
  "CODE": "PlantMaster-25224524",
  "NAME": "NAME-25224524",
  "CITY": "CITY-25224524"
}


### PlantMaster
# @name PlantMaster_DELETE
DELETE {{server}}/odata/v4/poplain/PlantMaster/PlantMaster-25224524
Content-Type: application/json
{{auth}}


### CompanyMaster
# @name CompanyMaster_GET
GET {{server}}/odata/v4/poplain/CompanyMaster
{{auth}}


### CompanyMaster
# @name CompanyMaster_POST
POST {{server}}/odata/v4/poplain/CompanyMaster
Content-Type: application/json
{{auth}}

{
  "CODE": "mpanyMaster-27004309",
  "DESC": "DESC-27004309",
  "WEBSITE": "WEBSITE-27004309",
  "NAME": "NAME-27004309"
}


### CompanyMaster
# @name CompanyMaster_PATCH
PATCH {{server}}/odata/v4/poplain/CompanyMaster/mpanyMaster-27004309
Content-Type: application/json
{{auth}}

{
  "CODE": "mpanyMaster-27004309",
  "DESC": "DESC-27004309",
  "WEBSITE": "WEBSITE-27004309",
  "NAME": "NAME-27004309"
}


### CompanyMaster
# @name CompanyMaster_DELETE
DELETE {{server}}/odata/v4/poplain/CompanyMaster/mpanyMaster-27004309
Content-Type: application/json
{{auth}}


### POEvent
# @name POEvent_GET
GET {{server}}/odata/v4/poplain/POEvent
{{auth}}


### POEvent
# @name POEvent_POST
POST {{server}}/odata/v4/poplain/POEvent
Content-Type: application/json
{{auth}}

{
  "PO_Number": 21657105,
  "EVENT_CODE": 21657105,
  "EVENT_DESCRIPTION": "EVENT_DESCRIPTION-21657105",
  "EVENT_DATE": "2016-10-31T00:00:00.000Z",
  "EVENT_BY": "EVENT_BY-21657105"
}


### POEvent
# @name POEvent_PATCH
PATCH {{server}}/odata/v4/poplain/POEvent(PO_Number=21657105,EVENT_CODE=21657105)
Content-Type: application/json
{{auth}}

{
  "PO_Number": 21657105,
  "EVENT_CODE": 21657105,
  "EVENT_DESCRIPTION": "EVENT_DESCRIPTION-21657105",
  "EVENT_DATE": "2016-10-31T00:00:00.000Z",
  "EVENT_BY": "EVENT_BY-21657105"
}


### POEvent
# @name POEvent_DELETE
DELETE {{server}}/odata/v4/poplain/POEvent(PO_Number=21657105,EVENT_CODE=21657105)
Content-Type: application/json
{{auth}}


### Material_Master
# @name Material_Master_GET
GET {{server}}/odata/v4/poplain/Material_Master
{{auth}}


### Material_Master
# @name Material_Master_POST
POST {{server}}/odata/v4/poplain/Material_Master
Content-Type: application/json
{{auth}}

{
  "CODE": "erial_Master-5808563",
  "DESC": "DESC-5808563",
  "Plant_Code": "Plant_Code-5808563",
  "Price": 50.596294,
  "Material_Image": "Material_Image-5808563",
  "Pl_Master": {
    "CODE": "PlantMaster-25224524"
  },
  "Phone": "Phone-5808563",
  "Fax": "Fax-5808563",
  "Email": "Email.3ghwz@example.com",
  "LandLine": "LandLine-5808563"
}


### Material_Master
# @name Material_Master_PATCH
PATCH {{server}}/odata/v4/poplain/Material_Master/erial_Master-5808563
Content-Type: application/json
{{auth}}

{
  "CODE": "erial_Master-5808563",
  "DESC": "DESC-5808563",
  "Plant_Code": "Plant_Code-5808563",
  "Price": 50.596294,
  "Material_Image": "Material_Image-5808563",
  "Pl_Master": {
    "CODE": "PlantMaster-25224524"
  },
  "Phone": "Phone-5808563",
  "Fax": "Fax-5808563",
  "Email": "Email.3ghwz@example.com",
  "LandLine": "LandLine-5808563"
}


### Material_Master
# @name Material_Master_DELETE
DELETE {{server}}/odata/v4/poplain/Material_Master/erial_Master-5808563
Content-Type: application/json
{{auth}}


### StatusMaster
# @name StatusMaster_GET
GET {{server}}/odata/v4/poplain/StatusMaster
{{auth}}


### StatusMaster
# @name StatusMaster_POST
POST {{server}}/odata/v4/poplain/StatusMaster
Content-Type: application/json
{{auth}}

{
  "CODE": 18168879,
  "DESC": "DESC-18168879"
}


### StatusMaster
# @name StatusMaster_PATCH
PATCH {{server}}/odata/v4/poplain/StatusMaster/18168879
Content-Type: application/json
{{auth}}

{
  "CODE": 18168879,
  "DESC": "DESC-18168879"
}


### StatusMaster
# @name StatusMaster_DELETE
DELETE {{server}}/odata/v4/poplain/StatusMaster/18168879
Content-Type: application/json
{{auth}}


### PO_Attachment
# @name PO_Attachment_GET
GET {{server}}/odata/v4/poplain/PO_Attachment
{{auth}}


### PO_Attachment
# @name PO_Attachment_POST
POST {{server}}/odata/v4/poplain/PO_Attachment
Content-Type: application/json
{{auth}}

{
  "ID": "1113953e-db6d-4f0b-9647-c7d259d4bb71",
  "PO_Number": 86,
  "File_Type": "File_Type-1113953",
  "FileName": "FileName-1113953",
  "createdAt": "2001-01-17T00:00:00.000Z",
  "createdBy": "createdBy.nvj5@example.org",
  "modifiedAt": "2013-02-19T00:00:00.000Z",
  "modifiedBy": "modifiedBy.nvj5@example.net"
}


### PO_Attachment
# @name PO_Attachment_PATCH
PATCH {{server}}/odata/v4/poplain/PO_Attachment/1113953e-db6d-4f0b-9647-c7d259d4bb71
Content-Type: application/json
{{auth}}

{
  "ID": "1113953e-db6d-4f0b-9647-c7d259d4bb71",
  "PO_Number": 86,
  "File_Type": "File_Type-1113953",
  "FileName": "FileName-1113953",
  "createdAt": "2001-01-17T00:00:00.000Z",
  "createdBy": "createdBy.nvj5@example.org",
  "modifiedAt": "2013-02-19T00:00:00.000Z",
  "modifiedBy": "modifiedBy.nvj5@example.net"
}


### PO_Attachment
# @name PO_Attachment_DELETE
DELETE {{server}}/odata/v4/poplain/PO_Attachment/1113953e-db6d-4f0b-9647-c7d259d4bb71
Content-Type: application/json
{{auth}}
