@server = http://localhost:4004
@auth = Authorization: Basic alice:


### NewAttachment
# @name NewAttachment_GET
GET {{server}}/odata/v4/poplain/NewAttachment
{{auth}}


### NewAttachment
# @name NewAttachment_POST
POST {{server}}/odata/v4/poplain/NewAttachment
Content-Type: application/json
{{auth}}

{
  "ID": "29311511-e1b4-4c82-8002-15906aa13bfa",
  "PO_Number": 23,
  "File_Type": "File_Type-29311511",
  "FileName": "FileName-29311511",
  "createdAt": "2014-12-07T18:30:00.000Z",
  "createdBy": "createdBy.hg8wn@example.net",
  "modifiedAt": "2008-02-10T18:30:00.000Z",
  "modifiedBy": "modifiedBy.hg8wn@example.net"
}


### NewAttachment
# @name NewAttachment_PATCH
PATCH {{server}}/odata/v4/poplain/NewAttachment/29311511-e1b4-4c82-8002-15906aa13bfa
Content-Type: application/json
{{auth}}

{
  "ID": "29311511-e1b4-4c82-8002-15906aa13bfa",
  "PO_Number": 23,
  "File_Type": "File_Type-29311511",
  "FileName": "FileName-29311511",
  "createdAt": "2014-12-07T18:30:00.000Z",
  "createdBy": "createdBy.hg8wn@example.net",
  "modifiedAt": "2008-02-10T18:30:00.000Z",
  "modifiedBy": "modifiedBy.hg8wn@example.net"
}


### NewAttachment
# @name NewAttachment_DELETE
DELETE {{server}}/odata/v4/poplain/NewAttachment/29311511-e1b4-4c82-8002-15906aa13bfa
Content-Type: application/json
{{auth}}
