@server = http://localhost:4004
@auth = Authorization: Basic alice:


# Service endpoint: odata/v4/potest/

### POHeader
# @name POHeader_GET
GET {{server}}/odata/v4/potest/POHeader
{{auth}}


### POHeader
# @name POHeader_POST
POST {{server}}/odata/v4/potest/POHeader
Content-Type: application/json
{{auth}}

{
  "ID": "2720644e-84e1-40ff-9ece-6d85baf48efb",
  "PO_Number": 97,
  "CreationDate": "2018-11-12",
  "DeliveryDate": "2011-01-08",
  "Status": 90,
  "MadeBy": "MadeBy-2720644",
  "PCode": "PCode-2720644",
  "CompanyCode": "CompanyCode-2720644",
  "Delete": "4",
  "Criticality": 90,
  "Total_Amount": 93.21,
  "Pl_Master": {
    "CODE": "PlantMaster-14410317"
  },
  "Cp_Master": {
    "CODE": "mpanyMaster-21641156"
  },
  "S_Master": {
    "CODE": 2754077
  },
  "PO_Item_Master": [
    {
      "ID": "15520110-0650-4983-86bd-1e5234934ba3",
      "PO_Number": 17,
      "PO_Item_Num": 75,
      "MCode": "MCode-15520110",
      "Quantity": 88,
      "Amount": 11.83,
      "M_Master": {
        "CODE": "rial_Master-19483388"
      }
    },
    {
      "ID": "15520111-2946-4346-8b8e-0c022dc73668",
      "PO_Number": 47,
      "PO_Item_Num": 13,
      "MCode": "MCode-15520111",
      "Quantity": 35,
      "Amount": 15.23,
      "M_Master": {
        "CODE": "rial_Master-19483388"
      }
    }
  ],
  "PO_Attach_Master": [
    {
      "ID": "24998144-e518-4bd2-8839-eac28ab3c669",
      "PO_Number": 88,
      "File_Type": "File_Type-24998144",
      "FileName": "FileName-24998144",
      "createdAt": "2022-03-10T18:30:00.000Z",
      "createdBy": "createdBy.evsow@example.net",
      "modifiedAt": "2004-07-23T18:30:00.000Z",
      "modifiedBy": "modifiedBy.evsow@example.org"
    },
    {
      "ID": "24998145-35e4-493f-ad85-ee2dcb3cd965",
      "PO_Number": 15,
      "File_Type": "File_Type-24998145",
      "FileName": "FileName-24998145",
      "createdAt": "2001-10-18T18:30:00.000Z",
      "createdBy": "createdBy.evsox@example.com",
      "modifiedAt": "2005-07-24T18:30:00.000Z",
      "modifiedBy": "modifiedBy.evsox@example.com"
    }
  ],
  "createdAt": "2001-06-28T18:30:00.000Z",
  "createdBy": "createdBy.1mb9g@example.net",
  "modifiedAt": "2004-03-16T18:30:00.000Z",
  "modifiedBy": "modifiedBy.1mb9g@example.net"
}


### POHeader
# @name POHeader_PATCH
PATCH {{server}}/odata/v4/potest/POHeader/2720644e-84e1-40ff-9ece-6d85baf48efb
Content-Type: application/json
{{auth}}

{
  "ID": "2720644e-84e1-40ff-9ece-6d85baf48efb",
  "PO_Number": 97,
  "CreationDate": "2018-11-12",
  "DeliveryDate": "2011-01-08",
  "Status": 90,
  "MadeBy": "MadeBy-2720644",
  "PCode": "PCode-2720644",
  "CompanyCode": "CompanyCode-2720644",
  "Delete": "4",
  "Criticality": 90,
  "Total_Amount": 93.21,
  "Pl_Master": {
    "CODE": "PlantMaster-14410317"
  },
  "Cp_Master": {
    "CODE": "mpanyMaster-21641156"
  },
  "S_Master": {
    "CODE": 2754077
  },
  "PO_Item_Master": [
    {
      "ID": "15520110-0650-4983-86bd-1e5234934ba3",
      "PO_Number": 17,
      "PO_Item_Num": 75,
      "MCode": "MCode-15520110",
      "Quantity": 88,
      "Amount": 11.83,
      "M_Master": {
        "CODE": "rial_Master-19483388"
      }
    },
    {
      "ID": "15520111-2946-4346-8b8e-0c022dc73668",
      "PO_Number": 47,
      "PO_Item_Num": 13,
      "MCode": "MCode-15520111",
      "Quantity": 35,
      "Amount": 15.23,
      "M_Master": {
        "CODE": "rial_Master-19483388"
      }
    }
  ],
  "PO_Attach_Master": [
    {
      "ID": "24998144-e518-4bd2-8839-eac28ab3c669",
      "PO_Number": 88,
      "File_Type": "File_Type-24998144",
      "FileName": "FileName-24998144",
      "createdAt": "2022-03-10T18:30:00.000Z",
      "createdBy": "createdBy.evsow@example.net",
      "modifiedAt": "2004-07-23T18:30:00.000Z",
      "modifiedBy": "modifiedBy.evsow@example.org"
    },
    {
      "ID": "24998145-35e4-493f-ad85-ee2dcb3cd965",
      "PO_Number": 15,
      "File_Type": "File_Type-24998145",
      "FileName": "FileName-24998145",
      "createdAt": "2001-10-18T18:30:00.000Z",
      "createdBy": "createdBy.evsox@example.com",
      "modifiedAt": "2005-07-24T18:30:00.000Z",
      "modifiedBy": "modifiedBy.evsox@example.com"
    }
  ],
  "createdAt": "2001-06-28T18:30:00.000Z",
  "createdBy": "createdBy.1mb9g@example.net",
  "modifiedAt": "2004-03-16T18:30:00.000Z",
  "modifiedBy": "modifiedBy.1mb9g@example.net"
}


### POHeader
# @name POHeader_DELETE
DELETE {{server}}/odata/v4/potest/POHeader/2720644e-84e1-40ff-9ece-6d85baf48efb
Content-Type: application/json
{{auth}}


### POItem
# @name POItem_GET
GET {{server}}/odata/v4/potest/POItem
{{auth}}


### POItem
# @name POItem_POST
POST {{server}}/odata/v4/potest/POItem
Content-Type: application/json
{{auth}}

{
  "ID": "15520110-0650-4983-86bd-1e5234934ba3",
  "PO_Number": 17,
  "PO_Item_Num": 75,
  "MCode": "MCode-15520110",
  "Quantity": 88,
  "Amount": 11.83,
  "M_Master": {
    "CODE": "rial_Master-19483388"
  }
}


### POItem
# @name POItem_PATCH
PATCH {{server}}/odata/v4/potest/POItem/15520110-0650-4983-86bd-1e5234934ba3
Content-Type: application/json
{{auth}}

{
  "ID": "15520110-0650-4983-86bd-1e5234934ba3",
  "PO_Number": 17,
  "PO_Item_Num": 75,
  "MCode": "MCode-15520110",
  "Quantity": 88,
  "Amount": 11.83,
  "M_Master": {
    "CODE": "rial_Master-19483388"
  }
}


### POItem
# @name POItem_DELETE
DELETE {{server}}/odata/v4/potest/POItem/15520110-0650-4983-86bd-1e5234934ba3
Content-Type: application/json
{{auth}}


### PlantMaster
# @name PlantMaster_GET
GET {{server}}/odata/v4/potest/PlantMaster
{{auth}}


### PlantMaster
# @name PlantMaster_POST
POST {{server}}/odata/v4/potest/PlantMaster
Content-Type: application/json
{{auth}}

{
  "CODE": "PlantMaster-14410317",
  "NAME": "NAME-14410317",
  "CITY": "CITY-14410317"
}


### PlantMaster
# @name PlantMaster_PATCH
PATCH {{server}}/odata/v4/potest/PlantMaster/PlantMaster-14410317
Content-Type: application/json
{{auth}}

{
  "CODE": "PlantMaster-14410317",
  "NAME": "NAME-14410317",
  "CITY": "CITY-14410317"
}


### PlantMaster
# @name PlantMaster_DELETE
DELETE {{server}}/odata/v4/potest/PlantMaster/PlantMaster-14410317
Content-Type: application/json
{{auth}}


### CompanyMaster
# @name CompanyMaster_GET
GET {{server}}/odata/v4/potest/CompanyMaster
{{auth}}


### CompanyMaster
# @name CompanyMaster_POST
POST {{server}}/odata/v4/potest/CompanyMaster
Content-Type: application/json
{{auth}}

{
  "CODE": "mpanyMaster-21641156",
  "DESC": "DESC-21641156",
  "WEBSITE": "WEBSITE-21641156",
  "NAME": "NAME-21641156"
}


### CompanyMaster
# @name CompanyMaster_PATCH
PATCH {{server}}/odata/v4/potest/CompanyMaster/mpanyMaster-21641156
Content-Type: application/json
{{auth}}

{
  "CODE": "mpanyMaster-21641156",
  "DESC": "DESC-21641156",
  "WEBSITE": "WEBSITE-21641156",
  "NAME": "NAME-21641156"
}


### CompanyMaster
# @name CompanyMaster_DELETE
DELETE {{server}}/odata/v4/potest/CompanyMaster/mpanyMaster-21641156
Content-Type: application/json
{{auth}}


### POEvent
# @name POEvent_GET
GET {{server}}/odata/v4/potest/POEvent
{{auth}}


### POEvent
# @name POEvent_POST
POST {{server}}/odata/v4/potest/POEvent
Content-Type: application/json
{{auth}}

{
  "PO_Number": 6000840,
  "EVENT_CODE": 6000840,
  "EVENT_DESCRIPTION": "EVENT_DESCRIPTION-6000840",
  "EVENT_DATE": "2005-01-27T18:30:00.000Z",
  "EVENT_BY": "EVENT_BY-6000840"
}


### POEvent
# @name POEvent_PATCH
PATCH {{server}}/odata/v4/potest/POEvent(PO_Number=6000840,EVENT_CODE=6000840)
Content-Type: application/json
{{auth}}

{
  "PO_Number": 6000840,
  "EVENT_CODE": 6000840,
  "EVENT_DESCRIPTION": "EVENT_DESCRIPTION-6000840",
  "EVENT_DATE": "2005-01-27T18:30:00.000Z",
  "EVENT_BY": "EVENT_BY-6000840"
}


### POEvent
# @name POEvent_DELETE
DELETE {{server}}/odata/v4/potest/POEvent(PO_Number=6000840,EVENT_CODE=6000840)
Content-Type: application/json
{{auth}}


### Material_Master
# @name Material_Master_GET
GET {{server}}/odata/v4/potest/Material_Master
{{auth}}


### Material_Master
# @name Material_Master_POST
POST {{server}}/odata/v4/potest/Material_Master
Content-Type: application/json
{{auth}}

{
  "CODE": "rial_Master-19483388",
  "DESC": "DESC-19483388",
  "Plant_Code": "Plant_Code-19483388",
  "Price": 37.31659094,
  "Material_Image": "Material_Image-19483388",
  "Pl_Master": {
    "CODE": "PlantMaster-14410317"
  },
  "Phone": "Phone-19483388",
  "Fax": "Fax-19483388",
  "Email": "Email.bllh8@example.org",
  "LandLine": "LandLine-19483388"
}


### Material_Master
# @name Material_Master_PATCH
PATCH {{server}}/odata/v4/potest/Material_Master/rial_Master-19483388
Content-Type: application/json
{{auth}}

{
  "CODE": "rial_Master-19483388",
  "DESC": "DESC-19483388",
  "Plant_Code": "Plant_Code-19483388",
  "Price": 37.31659094,
  "Material_Image": "Material_Image-19483388",
  "Pl_Master": {
    "CODE": "PlantMaster-14410317"
  },
  "Phone": "Phone-19483388",
  "Fax": "Fax-19483388",
  "Email": "Email.bllh8@example.org",
  "LandLine": "LandLine-19483388"
}


### Material_Master
# @name Material_Master_DELETE
DELETE {{server}}/odata/v4/potest/Material_Master/rial_Master-19483388
Content-Type: application/json
{{auth}}


### StatusMaster
# @name StatusMaster_GET
GET {{server}}/odata/v4/potest/StatusMaster
{{auth}}


### StatusMaster
# @name StatusMaster_POST
POST {{server}}/odata/v4/potest/StatusMaster
Content-Type: application/json
{{auth}}

{
  "CODE": 2754077,
  "DESC": "DESC-2754077"
}


### StatusMaster
# @name StatusMaster_PATCH
PATCH {{server}}/odata/v4/potest/StatusMaster/2754077
Content-Type: application/json
{{auth}}

{
  "CODE": 2754077,
  "DESC": "DESC-2754077"
}


### StatusMaster
# @name StatusMaster_DELETE
DELETE {{server}}/odata/v4/potest/StatusMaster/2754077
Content-Type: application/json
{{auth}}


### PO_Attachment
# @name PO_Attachment_GET
GET {{server}}/odata/v4/potest/PO_Attachment
{{auth}}


### PO_Attachment
# @name PO_Attachment_POST
POST {{server}}/odata/v4/potest/PO_Attachment
Content-Type: application/json
{{auth}}

{
  "ID": "24998144-e518-4bd2-8839-eac28ab3c669",
  "PO_Number": 88,
  "File_Type": "File_Type-24998144",
  "FileName": "FileName-24998144",
  "createdAt": "2022-03-10T18:30:00.000Z",
  "createdBy": "createdBy.evsow@example.net",
  "modifiedAt": "2004-07-23T18:30:00.000Z",
  "modifiedBy": "modifiedBy.evsow@example.org"
}


### PO_Attachment
# @name PO_Attachment_PATCH
PATCH {{server}}/odata/v4/potest/PO_Attachment/24998144-e518-4bd2-8839-eac28ab3c669
Content-Type: application/json
{{auth}}

{
  "ID": "24998144-e518-4bd2-8839-eac28ab3c669",
  "PO_Number": 88,
  "File_Type": "File_Type-24998144",
  "FileName": "FileName-24998144",
  "createdAt": "2022-03-10T18:30:00.000Z",
  "createdBy": "createdBy.evsow@example.net",
  "modifiedAt": "2004-07-23T18:30:00.000Z",
  "modifiedBy": "modifiedBy.evsow@example.org"
}


### PO_Attachment
# @name PO_Attachment_DELETE
DELETE {{server}}/odata/v4/potest/PO_Attachment/24998144-e518-4bd2-8839-eac28ab3c669
Content-Type: application/json
{{auth}}


# Service endpoint: graphql/potest/

### POHeader
# @name POHeader_GET
GET {{server}}/graphql/potest/POHeader
{{auth}}


### POHeader
# @name POHeader_POST
POST {{server}}/graphql/potest/POHeader
Content-Type: application/json
{{auth}}

{
  "ID": "2720644e-84e1-40ff-9ece-6d85baf48efb",
  "PO_Number": 97,
  "CreationDate": "2018-11-12",
  "DeliveryDate": "2011-01-08",
  "Status": 90,
  "MadeBy": "MadeBy-2720644",
  "PCode": "PCode-2720644",
  "CompanyCode": "CompanyCode-2720644",
  "Delete": "4",
  "Criticality": 90,
  "Total_Amount": 93.21,
  "Pl_Master": {
    "CODE": "PlantMaster-14410317"
  },
  "Cp_Master": {
    "CODE": "mpanyMaster-21641156"
  },
  "S_Master": {
    "CODE": 2754077
  },
  "PO_Item_Master": [
    {
      "ID": "15520110-0650-4983-86bd-1e5234934ba3",
      "PO_Number": 17,
      "PO_Item_Num": 75,
      "MCode": "MCode-15520110",
      "Quantity": 88,
      "Amount": 11.83,
      "M_Master": {
        "CODE": "rial_Master-19483388"
      }
    },
    {
      "ID": "15520111-2946-4346-8b8e-0c022dc73668",
      "PO_Number": 47,
      "PO_Item_Num": 13,
      "MCode": "MCode-15520111",
      "Quantity": 35,
      "Amount": 15.23,
      "M_Master": {
        "CODE": "rial_Master-19483388"
      }
    }
  ],
  "PO_Attach_Master": [
    {
      "ID": "24998144-e518-4bd2-8839-eac28ab3c669",
      "PO_Number": 88,
      "File_Type": "File_Type-24998144",
      "FileName": "FileName-24998144",
      "createdAt": "2022-03-10T18:30:00.000Z",
      "createdBy": "createdBy.evsow@example.net",
      "modifiedAt": "2004-07-23T18:30:00.000Z",
      "modifiedBy": "modifiedBy.evsow@example.org"
    },
    {
      "ID": "24998145-35e4-493f-ad85-ee2dcb3cd965",
      "PO_Number": 15,
      "File_Type": "File_Type-24998145",
      "FileName": "FileName-24998145",
      "createdAt": "2001-10-18T18:30:00.000Z",
      "createdBy": "createdBy.evsox@example.com",
      "modifiedAt": "2005-07-24T18:30:00.000Z",
      "modifiedBy": "modifiedBy.evsox@example.com"
    }
  ],
  "createdAt": "2001-06-28T18:30:00.000Z",
  "createdBy": "createdBy.1mb9g@example.net",
  "modifiedAt": "2004-03-16T18:30:00.000Z",
  "modifiedBy": "modifiedBy.1mb9g@example.net"
}


### POHeader
# @name POHeader_PATCH
PATCH {{server}}/graphql/potest/POHeader/2720644e-84e1-40ff-9ece-6d85baf48efb
Content-Type: application/json
{{auth}}

{
  "ID": "2720644e-84e1-40ff-9ece-6d85baf48efb",
  "PO_Number": 97,
  "CreationDate": "2018-11-12",
  "DeliveryDate": "2011-01-08",
  "Status": 90,
  "MadeBy": "MadeBy-2720644",
  "PCode": "PCode-2720644",
  "CompanyCode": "CompanyCode-2720644",
  "Delete": "4",
  "Criticality": 90,
  "Total_Amount": 93.21,
  "Pl_Master": {
    "CODE": "PlantMaster-14410317"
  },
  "Cp_Master": {
    "CODE": "mpanyMaster-21641156"
  },
  "S_Master": {
    "CODE": 2754077
  },
  "PO_Item_Master": [
    {
      "ID": "15520110-0650-4983-86bd-1e5234934ba3",
      "PO_Number": 17,
      "PO_Item_Num": 75,
      "MCode": "MCode-15520110",
      "Quantity": 88,
      "Amount": 11.83,
      "M_Master": {
        "CODE": "rial_Master-19483388"
      }
    },
    {
      "ID": "15520111-2946-4346-8b8e-0c022dc73668",
      "PO_Number": 47,
      "PO_Item_Num": 13,
      "MCode": "MCode-15520111",
      "Quantity": 35,
      "Amount": 15.23,
      "M_Master": {
        "CODE": "rial_Master-19483388"
      }
    }
  ],
  "PO_Attach_Master": [
    {
      "ID": "24998144-e518-4bd2-8839-eac28ab3c669",
      "PO_Number": 88,
      "File_Type": "File_Type-24998144",
      "FileName": "FileName-24998144",
      "createdAt": "2022-03-10T18:30:00.000Z",
      "createdBy": "createdBy.evsow@example.net",
      "modifiedAt": "2004-07-23T18:30:00.000Z",
      "modifiedBy": "modifiedBy.evsow@example.org"
    },
    {
      "ID": "24998145-35e4-493f-ad85-ee2dcb3cd965",
      "PO_Number": 15,
      "File_Type": "File_Type-24998145",
      "FileName": "FileName-24998145",
      "createdAt": "2001-10-18T18:30:00.000Z",
      "createdBy": "createdBy.evsox@example.com",
      "modifiedAt": "2005-07-24T18:30:00.000Z",
      "modifiedBy": "modifiedBy.evsox@example.com"
    }
  ],
  "createdAt": "2001-06-28T18:30:00.000Z",
  "createdBy": "createdBy.1mb9g@example.net",
  "modifiedAt": "2004-03-16T18:30:00.000Z",
  "modifiedBy": "modifiedBy.1mb9g@example.net"
}


### POHeader
# @name POHeader_DELETE
DELETE {{server}}/graphql/potest/POHeader/2720644e-84e1-40ff-9ece-6d85baf48efb
Content-Type: application/json
{{auth}}


### POItem
# @name POItem_GET
GET {{server}}/graphql/potest/POItem
{{auth}}


### POItem
# @name POItem_POST
POST {{server}}/graphql/potest/POItem
Content-Type: application/json
{{auth}}

{
  "ID": "15520110-0650-4983-86bd-1e5234934ba3",
  "PO_Number": 17,
  "PO_Item_Num": 75,
  "MCode": "MCode-15520110",
  "Quantity": 88,
  "Amount": 11.83,
  "M_Master": {
    "CODE": "rial_Master-19483388"
  }
}


### POItem
# @name POItem_PATCH
PATCH {{server}}/graphql/potest/POItem/15520110-0650-4983-86bd-1e5234934ba3
Content-Type: application/json
{{auth}}

{
  "ID": "15520110-0650-4983-86bd-1e5234934ba3",
  "PO_Number": 17,
  "PO_Item_Num": 75,
  "MCode": "MCode-15520110",
  "Quantity": 88,
  "Amount": 11.83,
  "M_Master": {
    "CODE": "rial_Master-19483388"
  }
}


### POItem
# @name POItem_DELETE
DELETE {{server}}/graphql/potest/POItem/15520110-0650-4983-86bd-1e5234934ba3
Content-Type: application/json
{{auth}}


### PlantMaster
# @name PlantMaster_GET
GET {{server}}/graphql/potest/PlantMaster
{{auth}}


### PlantMaster
# @name PlantMaster_POST
POST {{server}}/graphql/potest/PlantMaster
Content-Type: application/json
{{auth}}

{
  "CODE": "PlantMaster-14410317",
  "NAME": "NAME-14410317",
  "CITY": "CITY-14410317"
}


### PlantMaster
# @name PlantMaster_PATCH
PATCH {{server}}/graphql/potest/PlantMaster/PlantMaster-14410317
Content-Type: application/json
{{auth}}

{
  "CODE": "PlantMaster-14410317",
  "NAME": "NAME-14410317",
  "CITY": "CITY-14410317"
}


### PlantMaster
# @name PlantMaster_DELETE
DELETE {{server}}/graphql/potest/PlantMaster/PlantMaster-14410317
Content-Type: application/json
{{auth}}


### CompanyMaster
# @name CompanyMaster_GET
GET {{server}}/graphql/potest/CompanyMaster
{{auth}}


### CompanyMaster
# @name CompanyMaster_POST
POST {{server}}/graphql/potest/CompanyMaster
Content-Type: application/json
{{auth}}

{
  "CODE": "mpanyMaster-21641156",
  "DESC": "DESC-21641156",
  "WEBSITE": "WEBSITE-21641156",
  "NAME": "NAME-21641156"
}


### CompanyMaster
# @name CompanyMaster_PATCH
PATCH {{server}}/graphql/potest/CompanyMaster/mpanyMaster-21641156
Content-Type: application/json
{{auth}}

{
  "CODE": "mpanyMaster-21641156",
  "DESC": "DESC-21641156",
  "WEBSITE": "WEBSITE-21641156",
  "NAME": "NAME-21641156"
}


### CompanyMaster
# @name CompanyMaster_DELETE
DELETE {{server}}/graphql/potest/CompanyMaster/mpanyMaster-21641156
Content-Type: application/json
{{auth}}


### POEvent
# @name POEvent_GET
GET {{server}}/graphql/potest/POEvent
{{auth}}


### POEvent
# @name POEvent_POST
POST {{server}}/graphql/potest/POEvent
Content-Type: application/json
{{auth}}

{
  "PO_Number": 6000840,
  "EVENT_CODE": 6000840,
  "EVENT_DESCRIPTION": "EVENT_DESCRIPTION-6000840",
  "EVENT_DATE": "2005-01-27T18:30:00.000Z",
  "EVENT_BY": "EVENT_BY-6000840"
}


### POEvent
# @name POEvent_PATCH
PATCH {{server}}/graphql/potest/POEvent(PO_Number=6000840,EVENT_CODE=6000840)
Content-Type: application/json
{{auth}}

{
  "PO_Number": 6000840,
  "EVENT_CODE": 6000840,
  "EVENT_DESCRIPTION": "EVENT_DESCRIPTION-6000840",
  "EVENT_DATE": "2005-01-27T18:30:00.000Z",
  "EVENT_BY": "EVENT_BY-6000840"
}


### POEvent
# @name POEvent_DELETE
DELETE {{server}}/graphql/potest/POEvent(PO_Number=6000840,EVENT_CODE=6000840)
Content-Type: application/json
{{auth}}


### Material_Master
# @name Material_Master_GET
GET {{server}}/graphql/potest/Material_Master
{{auth}}


### Material_Master
# @name Material_Master_POST
POST {{server}}/graphql/potest/Material_Master
Content-Type: application/json
{{auth}}

{
  "CODE": "rial_Master-19483388",
  "DESC": "DESC-19483388",
  "Plant_Code": "Plant_Code-19483388",
  "Price": 37.31659094,
  "Material_Image": "Material_Image-19483388",
  "Pl_Master": {
    "CODE": "PlantMaster-14410317"
  },
  "Phone": "Phone-19483388",
  "Fax": "Fax-19483388",
  "Email": "Email.bllh8@example.org",
  "LandLine": "LandLine-19483388"
}


### Material_Master
# @name Material_Master_PATCH
PATCH {{server}}/graphql/potest/Material_Master/rial_Master-19483388
Content-Type: application/json
{{auth}}

{
  "CODE": "rial_Master-19483388",
  "DESC": "DESC-19483388",
  "Plant_Code": "Plant_Code-19483388",
  "Price": 37.31659094,
  "Material_Image": "Material_Image-19483388",
  "Pl_Master": {
    "CODE": "PlantMaster-14410317"
  },
  "Phone": "Phone-19483388",
  "Fax": "Fax-19483388",
  "Email": "Email.bllh8@example.org",
  "LandLine": "LandLine-19483388"
}


### Material_Master
# @name Material_Master_DELETE
DELETE {{server}}/graphql/potest/Material_Master/rial_Master-19483388
Content-Type: application/json
{{auth}}


### StatusMaster
# @name StatusMaster_GET
GET {{server}}/graphql/potest/StatusMaster
{{auth}}


### StatusMaster
# @name StatusMaster_POST
POST {{server}}/graphql/potest/StatusMaster
Content-Type: application/json
{{auth}}

{
  "CODE": 2754077,
  "DESC": "DESC-2754077"
}


### StatusMaster
# @name StatusMaster_PATCH
PATCH {{server}}/graphql/potest/StatusMaster/2754077
Content-Type: application/json
{{auth}}

{
  "CODE": 2754077,
  "DESC": "DESC-2754077"
}


### StatusMaster
# @name StatusMaster_DELETE
DELETE {{server}}/graphql/potest/StatusMaster/2754077
Content-Type: application/json
{{auth}}


### PO_Attachment
# @name PO_Attachment_GET
GET {{server}}/graphql/potest/PO_Attachment
{{auth}}


### PO_Attachment
# @name PO_Attachment_POST
POST {{server}}/graphql/potest/PO_Attachment
Content-Type: application/json
{{auth}}

{
  "ID": "24998144-e518-4bd2-8839-eac28ab3c669",
  "PO_Number": 88,
  "File_Type": "File_Type-24998144",
  "FileName": "FileName-24998144",
  "createdAt": "2022-03-10T18:30:00.000Z",
  "createdBy": "createdBy.evsow@example.net",
  "modifiedAt": "2004-07-23T18:30:00.000Z",
  "modifiedBy": "modifiedBy.evsow@example.org"
}


### PO_Attachment
# @name PO_Attachment_PATCH
PATCH {{server}}/graphql/potest/PO_Attachment/24998144-e518-4bd2-8839-eac28ab3c669
Content-Type: application/json
{{auth}}

{
  "ID": "24998144-e518-4bd2-8839-eac28ab3c669",
  "PO_Number": 88,
  "File_Type": "File_Type-24998144",
  "FileName": "FileName-24998144",
  "createdAt": "2022-03-10T18:30:00.000Z",
  "createdBy": "createdBy.evsow@example.net",
  "modifiedAt": "2004-07-23T18:30:00.000Z",
  "modifiedBy": "modifiedBy.evsow@example.org"
}


### PO_Attachment
# @name PO_Attachment_DELETE
DELETE {{server}}/graphql/potest/PO_Attachment/24998144-e518-4bd2-8839-eac28ab3c669
Content-Type: application/json
{{auth}}
