@server = http://localhost:4004
## UPDATE
PATCH {{server}}/odata/v4/pocreation/PlantMaster/ZMRO
Content-Type: application/json

{
     "CITY": "Washington D.C."
}

### Create Plant Master
DELETE {{server}}/odata/v4/pocreation/PlantMaster/ZUSA
Content-Type: application/json

{
    "CODE": "ZUSA",
    "NAME": "US Roller Coaster",
    "CITY": "Ohio"      
}